"""empty message

Revision ID: 56415c3857ef
Revises: 0c9e602e4536
Create Date: 2021-05-14 15:02:06.402631

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56415c3857ef'
down_revision = '0c9e602e4536'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('artists', 'website_link')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artists', sa.Column('website_link', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
